'use strict';
const name = 'название: Генератор защитного поля';
let price = 'цена: 1000';
console.log(name);
console.log(price);
let sameMessage = 'Выбран "Генератор защитного поля", цена за штуку 1000 кредитов';
console.log(sameMessage);
price = 'цена: 2000';
sameMessage = 'Выбран "Генератор защитного поля", цена за штуку 2000 кредитов';
console.log(sameMessage);